### ISSUE TITLE
Using pre calculated PCA / normalization

### ISSUE THREAD

**Issue by pakiessling** [imsb-uke/nichepca#1]
### Description of feature

Hi,

I have a dataset of about 2 million cells which I integrated with rapids single cell on gpu.
I got much better results by using z-scores for every samples separately followed by harmony.
Is there a way to reuse these (lenghty) processing steps for nichepca or do I have to start from counts?

Ty!

**Comment by pakiessling** [comment]
No I dont think I will do that russian bot

**Comment by dschaub95** [comment]
Hi,

sorry for the late reply!

I fear you have to start from counts since you need to first run the aggregation before applying PCA and harmony.

Best
Darius

**Comment by pakiessling** [comment]
ok, ty!
